2025-10-31 17:51:01,824 - INFO - Iniciando pipeline de e-commerce...
2025-10-31 17:51:01,824 - INFO - Descargando datos desde la API: https://fakestoreapi.com/products
2025-10-31 17:51:02,529 - INFO - Datos descargados correctamente: 20 productos.
2025-10-31 17:51:02,530 - INFO - Cargando CSV: data/raw/sales.csv
2025-10-31 17:51:02,543 - INFO - Archivo data/raw/sales.csv cargado con 12 filas y 5 columnas.
2025-10-31 17:51:02,544 - INFO - Cargando CSV: data/raw/inventory.csv
2025-10-31 17:51:02,553 - INFO - Archivo data/raw/inventory.csv cargado con 12 filas y 3 columnas.
2025-10-31 17:51:02,554 - INFO - Guardando DataFrame en Parquet: data/raw\products_2025-10-31.parquet
2025-10-31 17:51:02,555 - ERROR - Error en la etapa de ingesta
Traceback (most recent call last):
  File "C:\Users\toby7\Downloads\proyecto-parcial\src\orchestrator.py", line 55, in run_pipeline
    save_parquet(products_df, products_raw_path)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toby7\Downloads\proyecto-parcial\src\ingestion.py", line 33, in save_parquet
    df.to_parquet(output_path, index=False)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toby7\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\toby7\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\frame.py", line 3124, in to_parquet
    return to_parquet(
        self,
    ...<6 lines>...
        **kwargs,
    )
  File "C:\Users\toby7\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\parquet.py", line 478, in to_parquet
    impl = get_engine(engine)
  File "C:\Users\toby7\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\parquet.py", line 68, in get_engine
    raise ImportError(
    ...<7 lines>...
    )
ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
2025-10-31 17:54:57,607 - INFO - Iniciando pipeline de e-commerce...
2025-10-31 17:54:57,607 - INFO - Descargando datos desde la API: https://fakestoreapi.com/products
2025-10-31 17:54:58,317 - INFO - Datos descargados correctamente: 20 productos.
2025-10-31 17:54:58,319 - INFO - Cargando CSV: data/raw/sales.csv
2025-10-31 17:54:58,322 - INFO - Archivo data/raw/sales.csv cargado con 12 filas y 5 columnas.
2025-10-31 17:54:58,322 - INFO - Cargando CSV: data/raw/inventory.csv
2025-10-31 17:54:58,324 - INFO - Archivo data/raw/inventory.csv cargado con 12 filas y 3 columnas.
2025-10-31 17:54:58,324 - INFO - Guardando DataFrame en Parquet: data/raw\products_2025-10-31.parquet
2025-10-31 17:54:58,515 - INFO - Archivo guardado correctamente.
2025-10-31 17:54:58,515 - INFO - Guardando DataFrame en Parquet: data/raw\sales_2025-10-31.parquet
2025-10-31 17:54:58,519 - INFO - Archivo guardado correctamente.
2025-10-31 17:54:58,519 - INFO - Guardando DataFrame en Parquet: data/raw\inventory_2025-10-31.parquet
2025-10-31 17:54:58,522 - INFO - Archivo guardado correctamente.
2025-10-31 17:54:58,522 - INFO - Merging data: products + sales + inventory
2025-10-31 17:54:58,533 - INFO - Computing business metrics
2025-10-31 17:54:58,534 - ERROR - Error en transformación
Traceback (most recent call last):
  File "C:\Users\toby7\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    return self._engine.get_loc(casted_key)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7096, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'price'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\toby7\Downloads\proyecto-parcial\src\orchestrator.py", line 64, in run_pipeline
    metrics = compute_metrics(merged)
  File "C:\Users\toby7\Downloads\proyecto-parcial\src\transformation.py", line 38, in compute_metrics
    df['price'] = pd.to_numeric(df['price'], errors='coerce').fillna(0.0)
                                ~~^^^^^^^^^
  File "C:\Users\toby7\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\frame.py", line 4113, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\toby7\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\indexes\base.py", line 3819, in get_loc
    raise KeyError(key) from err
KeyError: 'price'
2025-10-31 18:01:57,125 - INFO - Iniciando pipeline de e-commerce...
2025-10-31 18:01:57,126 - INFO - Descargando datos desde la API: https://fakestoreapi.com/products
2025-10-31 18:01:58,197 - INFO - Datos descargados correctamente: 20 productos.
2025-10-31 18:01:58,198 - INFO - Cargando CSV: data/raw/sales.csv
2025-10-31 18:01:58,201 - INFO - Archivo data/raw/sales.csv cargado con 12 filas y 5 columnas.
2025-10-31 18:01:58,202 - INFO - Cargando CSV: data/raw/inventory.csv
2025-10-31 18:01:58,203 - INFO - Archivo data/raw/inventory.csv cargado con 12 filas y 3 columnas.
2025-10-31 18:01:58,203 - INFO - Guardando DataFrame en Parquet: data/raw\products_2025-10-31.parquet
2025-10-31 18:01:58,227 - INFO - Archivo guardado correctamente.
2025-10-31 18:01:58,227 - INFO - Guardando DataFrame en Parquet: data/raw\sales_2025-10-31.parquet
2025-10-31 18:01:58,231 - INFO - Archivo guardado correctamente.
2025-10-31 18:01:58,231 - INFO - Guardando DataFrame en Parquet: data/raw\inventory_2025-10-31.parquet
2025-10-31 18:01:58,234 - INFO - Archivo guardado correctamente.
2025-10-31 18:01:58,234 - INFO - Merging data: products + sales + inventory
2025-10-31 18:01:58,240 - INFO - Computing business metrics
2025-10-31 18:01:58,259 - INFO - Check: no negative prices
2025-10-31 18:01:58,259 - INFO - Check: stock integer positive
2025-10-31 18:01:58,261 - INFO - Check: categories exist
2025-10-31 18:01:58,261 - INFO - Check: sale dates valid
2025-10-31 18:01:58,264 - INFO - Quality checks pasaron correctamente
2025-10-31 18:01:58,276 - INFO - Outputs generados y guardados
2025-10-31 18:01:58,278 - INFO - Reporte simple generado: data/outputs\report_2025-10-31.md
2025-10-31 18:01:58,279 - INFO - Pipeline finalizado correctamente
